"use strict";

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert(
      "makers",
      [
        { name: "AXIS GOLF", createdAt: new Date(), updatedAt: new Date() },
        { name: "アキラ", createdAt: new Date(), updatedAt: new Date() },
        { name: "ADLLER", createdAt: new Date(), updatedAt: new Date() },
        { name: "EVEN GOLF", createdAt: new Date(), updatedAt: new Date() },
        {
          name: "イオンスポーツ",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { name: "ウィンバード", createdAt: new Date(), updatedAt: new Date() },
        { name: "A.F.D.", createdAt: new Date(), updatedAt: new Date() },
        { name: "A デザイン", createdAt: new Date(), updatedAt: new Date() },
        { name: "ESTIVANT", createdAt: new Date(), updatedAt: new Date() },
        {
          name: "EMILLID BAHAMA",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { name: "MTG ITOBORI", createdAt: new Date(), updatedAt: new Date() },
        { name: "エポン", createdAt: new Date(), updatedAt: new Date() },
        { name: "カムイ", createdAt: new Date(), updatedAt: new Date() },
        { name: "キャスコ", createdAt: new Date(), updatedAt: new Date() },
        {
          name: "KING LOVE QUEEN",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { name: "キャロウェイ", createdAt: new Date(), updatedAt: new Date() },
        { name: "グラビティ", createdAt: new Date(), updatedAt: new Date() },
        {
          name: "グランディスタ",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Crime of Angel",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { name: "グランプリ", createdAt: new Date(), updatedAt: new Date() },
        { name: "クレイジー", createdAt: new Date(), updatedAt: new Date() },
        { name: "KENT", createdAt: new Date(), updatedAt: new Date() },
        { name: "コブラ", createdAt: new Date(), updatedAt: new Date() },
        { name: "ゴリラ", createdAt: new Date(), updatedAt: new Date() },
        {
          name: "GEORGE SPIRITS",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { name: "GTD", createdAt: new Date(), updatedAt: new Date() },
        { name: "JBEAM", createdAt: new Date(), updatedAt: new Date() },
        { name: "Jean-Baptiste", createdAt: new Date(), updatedAt: new Date() },
        { name: "Jean-Carlo", createdAt: new Date(), updatedAt: new Date() },
        {
          name: "ジャスティック",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { name: "ゾディア", createdAt: new Date(), updatedAt: new Date() },
        { name: "タイトリスト", createdAt: new Date(), updatedAt: new Date() },
        {
          name: "ダイワ(グローブライド)",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { name: "ダンロップ", createdAt: new Date(), updatedAt: new Date() },
        {
          name: "チーム ヨシムラ",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { name: "TRPX", createdAt: new Date(), updatedAt: new Date() },
        { name: "Design Tuning", createdAt: new Date(), updatedAt: new Date() },
        {
          name: "テーラーメイド",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { name: "ナイキ", createdAt: new Date(), updatedAt: new Date() },
        { name: "日幸物産", createdAt: new Date(), updatedAt: new Date() },
        { name: "BUDDY", createdAt: new Date(), updatedAt: new Date() },
        { name: "Haraken", createdAt: new Date(), updatedAt: new Date() },
        { name: "バルド", createdAt: new Date(), updatedAt: new Date() },
        { name: "PXG", createdAt: new Date(), updatedAt: new Date() },
        { name: "P-TUNE", createdAt: new Date(), updatedAt: new Date() },
        { name: "ピン", createdAt: new Date(), updatedAt: new Date() },
        {
          name: "フォーティーン",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { name: "フライハイト", createdAt: new Date(), updatedAt: new Date() },
        { name: "ブリヂストン", createdAt: new Date(), updatedAt: new Date() },
        { name: "PRGR", createdAt: new Date(), updatedAt: new Date() },
        { name: "PROGRESS", createdAt: new Date(), updatedAt: new Date() },
        { name: "本間ゴルフ", createdAt: new Date(), updatedAt: new Date() },
        { name: "マグレガー", createdAt: new Date(), updatedAt: new Date() },
        { name: "マスダ", createdAt: new Date(), updatedAt: new Date() },
        { name: "マスターズ", createdAt: new Date(), updatedAt: new Date() },
        {
          name: "マックスソウル",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { name: "マルマン", createdAt: new Date(), updatedAt: new Date() },
        { name: "三浦技研", createdAt: new Date(), updatedAt: new Date() },
        { name: "ミステリー", createdAt: new Date(), updatedAt: new Date() },
        { name: "ミズノ", createdAt: new Date(), updatedAt: new Date() },
        { name: "ミライ", createdAt: new Date(), updatedAt: new Date() },
        { name: "ムジーク", createdAt: new Date(), updatedAt: new Date() },
        {
          name: "メタルファクトリー",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        { name: "MODART", createdAt: new Date(), updatedAt: new Date() },
        { name: "ヤマハ", createdAt: new Date(), updatedAt: new Date() },
        { name: "ヨネックス", createdAt: new Date(), updatedAt: new Date() },
        { name: "リョーマ", createdAt: new Date(), updatedAt: new Date() },
        { name: "REVE", createdAt: new Date(), updatedAt: new Date() },
        { name: "ロマロ", createdAt: new Date(), updatedAt: new Date() },
        { name: "WAOWW", createdAt: new Date(), updatedAt: new Date() },
        { name: "その他", createdAt: new Date(), updatedAt: new Date() },
      ],
      {}
    );
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("makers", null, {});
  },
};
