import { BASICCOLORS } from '../../../utils/constant/color';

interface ICOLOR {
  color: COLORTYPES;
}

type COLORTYPES =
  | typeof BASICCOLORS.PRIMARY
  | typeof BASICCOLORS.PRIMARYDARK
  | typeof BASICCOLORS.PRIMARYLIGHT
  | typeof BASICCOLORS.SECONDARY
  | typeof BASICCOLORS.SECONDARYDARK
  | typeof BASICCOLORS.SECONDARYLIGHT
  | typeof BASICCOLORS.BASIC
  | typeof BASICCOLORS.BASICDARK
  | typeof BASICCOLORS.BASICLIGHT
  | typeof BASICCOLORS.WHITE
  | typeof BASICCOLORS.WHITEDARK
  | typeof BASICCOLORS.WHITELIGHT
  | typeof BASICCOLORS.CAUTION;

type PartialICOLOR = Partial<ICOLOR>;
