- name: setup nodejs12.x
  shell: curl -sL https://rpm.nodesource.com/setup_12.x | bash -

- name: installing 12.x version of node.js
  yum:
    name: nodejs
    state: latest

- name: add baseExpress
  copy:
    src: "roles/node/files/baseExpress"
    dest: "/opt"
    owner: root
    group: root
    mode: 0644

- name: Install packages based on package.json.
  npm:
    path: /opt/baseExpress